name: Setup repository for CI tests
runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18.x
    - run: yarn --immutable --immutable-cache --check-cache
