name: CI Checks
on:
  push:
  pull_request:
  merge_group:

jobs:
  yarn:
    runs-on: ubuntu-latest
    steps:
      - uses: .github/actions/setup

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: .github/actions/setup
      - run: yarn test

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: .github/actions/setup
      - run: yarn build --env production

  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: .github/actions/setup
      - run: yarn lint:eslint

  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: .github/actions/setup
      - run: yarn lint:prettier

  tsc:
    runs-on: ubuntu-latest
    steps:
      - uses: .github/actions/setup
      - run: yarn lint:tsc
